// Senior Insurance Data based on AAR, Jubilee, and CIC documentation
export const insuranceCompanies = [
  {
    id: "1",
    name: "Jubilee Insurance",
    contactEmail: "info@jubilee.co.ke",
    contactPhone: "+254 20 328 1000",
    headquarters: "Nairobi, Kenya",
    logo: "/jubilee.png",
    description:
      "Jubilee Health Insurance Ltd is a leading Medical Insurer in East Africa, providing tailored first-class health insurance products to suit individual and corporate needs.",
  },
  {
    id: "2",
    name: "AAR Insurance",
    contactEmail: "info@aar.co.ke",
    contactPhone: "+254 20 286 2000",
    headquarters: "Nairobi, Kenya",
    logo: "/aar.png",
    description:
      "AAR Insurance provides comprehensive healthcare solutions for seniors with a variety of plans designed to meet the needs of the elderly population.",
  },
  {
    id: "3",
    name: "CIC Insurance",
    contactEmail: "info@cic.co.ke",
    contactPhone: "+254 20 282 3000",
    headquarters: "Nairobi, Kenya",
    logo: "/cic.png",
    description:
      "CIC Insurance offers tiered plans specifically designed for senior citizens, providing comprehensive coverage options for various healthcare needs.",
  },
  {
    id: "4",
    name: "Britam Insurance",
    contactEmail: "info@britam.co.ke",
    contactPhone: "+254 20 282 3000",
    headquarters: "Nairobi, Kenya",
    logo: "/britam.png",
    description:
      "Britam Insurance offers tiered plans specifically designed for senior citizens, providing comprehensive coverage options for various healthcare needs.",
  },
  {
    id: "5",
    name: "Madison Insurance",
    contactEmail: "info@madison.co.ke",
    contactPhone: "+254 20 282 3000",
    headquarters: "Nairobi, Kenya",
    logo: "/madison.png",
    description:
      "Madison Insurance offers tiered plans specifically designed for senior citizens, providing comprehensive coverage options for various healthcare needs.",
  },
  {
    id: "6",
    name: "Germinia Insurance",
    contactEmail: "info@germinia.co.ke",
    contactPhone: "+254 20 282 3000",
    headquarters: "Nairobi, Kenya",
    logo: "/germinia.png",
    description:
      "Germinia Insurance offers tiered plans specifically designed for senior citizens, providing comprehensive coverage options for various healthcare needs.",
  },
  
];

// Plans organized by company with real world data
export const insurancePlans = [
  // Jubilee Insurance Plans (5 tiers)
  {
    id: "1",
    companyId: "1",
    name: "Jubilee Copper",
    planType: "Copper",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 79,
    inpatientCoverageLimit: 500000,
    outpatientCoverageLimit: 100000,
    lastExpenseCover: 50000,
    annualPremium: {
      "65-69": 57952,
      "70-74": 68819,
      "75-79": 72441,
    },
    bedLimit: "General Ward",
    roomRate: "General Ward",
    companyName: "Jubilee Insurance",
    companyLogo: "/jubilee.png",
    dentalCovered: true,
    opticalCovered: true,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 0,
    opticalPremium: 0,
  },
  {
    id: "2",
    companyId: "1",
    name: "Jubilee Bronze",
    planType: "Bronze",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 79,
    inpatientCoverageLimit: 1000000,
    outpatientCoverageLimit: 100000,
    lastExpenseCover: 50000,
    annualPremium: {
      "65-69": 81063,
      "70-74": 96264,
      "75-79": 101330,
    },
    bedLimit: "General Ward",
    roomRate: "General Ward",
    companyName: "Jubilee Insurance",
    companyLogo: "/jubilee.png",
    dentalCovered: false,
    opticalCovered: false,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 0,
    opticalPremium: 0,
  },
  {
    id: "3",
    companyId: "1",
    name: "Jubilee Silver",
    planType: "Enhanced",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 79,
    inpatientCoverageLimit: 3000000,
    outpatientCoverageLimit: 150000,
    lastExpenseCover: 75000,
    annualPremium: {
      "65-69": 121067,
      "70-74": 143766,
      "75-79": 151333,
    },
    bedLimit: "Standard Private Room up to 12,500",
    roomRate: "Standard Private Room",
    companyName: "Jubilee Insurance",
    companyLogo: "/jubilee.png",
    dentalCovered: true,
    opticalCovered: true,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 0,
    opticalPremium: 0,
  },
  {
    id: "4",
    companyId: "1",
    name: "Jubilee Gold",
    planType: "Premium",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 79,
    inpatientCoverageLimit: 5000000,
    outpatientCoverageLimit: 200000,
    lastExpenseCover: 100000,
    annualPremium: {
      "65-69": 139806,
      "70-74": 166019,
      "75-79": 174757,
    },
    bedLimit: "Standard Private Room up to 24,000",
    roomRate: "Deluxe",
    companyName: "Jubilee Insurance",
    companyLogo: "/jubilee.png",
    dentalCovered: true,
    opticalCovered: true,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 0,
    opticalPremium: 0,
  },
  {
    id: "5",
    companyId: "1",
    name: "Jubilee Diamond",
    planType: "Executive",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 79,
    inpatientCoverageLimit: 10000000,
    outpatientCoverageLimit: 200000,
    lastExpenseCover: 100000,
    annualPremium: {
      "65-69": 182754,
      "70-74": 217020,
      "75-79": 228443,
    },
    bedLimit: "Standard Private Room up to 32,000",
    roomRate: "Executive",
    companyName: "Jubilee Insurance",
    companyLogo: "/jubilee.png",
    dentalCovered: true,
    opticalCovered: true,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 0,
    opticalPremium: 0,
  },

  // AAR Insurance Plans (6 tiers)
  {
    id: "6",
    companyId: "2",
    name: "AAR Copper",
    planType: "Basic",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 85,
    inpatientCoverageLimit: 500000,
    outpatientCoverageLimit: 50000,
    lastExpenseCover: 75000,
    annualPremium: {
      "65-70": 55714,
      "71-85": 74100,
    },
    bedLimit: "General Ward - Max 10,000",
    roomRate: "General Ward",
    companyName: "AAR Insurance",
    companyLogo: "/aar.png",
    dentalCovered: false,
    opticalCovered: false,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 0,
    opticalPremium: 0,
  },
  {
    id: "7",
    companyId: "2",
    name: "AAR Bronze",
    planType: "Standard",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 85,
    inpatientCoverageLimit: 1000000,
    outpatientCoverageLimit: 75000,
    lastExpenseCover: 100000,
    annualPremiumm: {
      "65-70": 76329,
      "71-85": 101517,
    },
    bedLimit: "General Ward - Max 10,000",
    roomRate: "General Ward",
    companyName: "AAR Insurance",
    companyLogo: "/aar.png",
    dentalCovered: false,
    opticalCovered: false,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 10000,
    opticalPremium: 8000,
  },
  {
    id: "8",
    companyId: "2",
    name: "AAR Silver",
    planType: "Enhanced",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 85,
    inpatientCoverageLimit: 2000000,
    outpatientCoverageLimit: 100000,
    lastExpenseCover: 100000,
    annualPremium: {
      "65-70": 99227,
      "71-85": 131972,
    },
    bedLimit: "Private Room - 12,000",
    roomRate: "Private Room",
    companyName: "AAR Insurance",
    companyLogo: "/aar.png",
    dentalCovered: false,
    opticalCovered: false,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 10000,
    opticalPremium: 8000,
  },
  {
    id: "9",
    companyId: "2",
    name: "AAR Gold",
    planType: "Premium",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 85,
    inpatientCoverageLimit: 3000000,
    outpatientCoverageLimit: 150000,
    lastExpenseCover: 100000,
    annualPremium: {
      "65-70": 114493,
      "71-85": 152276,
    },
    bedLimit: "Private Room - 16,000",
    roomRate: "Private Room",
    companyName: "AAR Insurance",
    companyLogo: "/aar.png",
    dentalCovered: false,
    opticalCovered: false,
    maternityCovered: false,
    dentalCoverageLimit: 30000,
    opticalCoverageLimit: 30000,
    maternityCoverageLimit: 0,
    dentalPremium: 10000,
    opticalPremium: 8000,
  },
  {
    id: "10",
    companyId: "2",
    name: "AAR Diamond",
    planType: "Executive",
    eligibilityAgeMin: 65,
    eligibilityAgeMax: 85,
    inpatientCoverageLimit: 5000000,
    outpatientCoverageLimit: 200000,
    lastExpenseCover: 150000,
    premium: {
      "65-70": 143879,
      "71-85": 191360,
    },
    bedLimit: "Private Room - Max 20,000",
    roomRate: "Deluxe Private Room",
    companyName: "AAR Insurance",
    companyLogo: "/aar.png",
  },
  {
    id: "11",
    companyId: "2",
    name: "AAR Platinum",
    tier: "Platinum",
    planType: "Royal",
    eligibilityAge: "65-85",
    inpatientCoverageLimit: 10000000,
    outpatientCoverageLimit: 250000,
    lastExpenseCover: 200000,
    premium: {
      "65-70": 175533,
      "71-85": 233459,
    },
    bedLimit: "Ensuite - Max 30,000",
    roomRate: "Ensuite",
    companyName: "AAR Insurance",
    companyLogo: "/aar.png",
  },

  // CIC Insurance Plans (6 tiers)
  {
    id: "12",
    companyId: "3",
    name: "CIC Plan I",
    tier: "Plan I",
    planType: "Basic",
    eligibilityAge: "65-85",
    inpatientCoverageLimit: 300000,
    outpatientCoverageLimit: 50000,
    lastExpenseCover: 50000,
    premium: 48000, // Using approximate figure based on comparable plans
    bedLimit: "General Ward Bed",
    roomRate: "General Ward",
    companyName: "CIC Insurance",
    companyLogo: "/cic.png",
  },
  {
    id: "13",
    companyId: "3",
    name: "CIC Plan II",
    tier: "Plan II",
    planType: "Standard",
    eligibilityAge: "65-85",
    inpatientCoverageLimit: 500000,
    outpatientCoverageLimit: 75000,
    lastExpenseCover: 60000,
    premium: 56000, // Using approximate figure based on comparable plans
    bedLimit: "General Ward Bed",
    roomRate: "General Ward",
    companyName: "CIC Insurance",
    companyLogo: "/cic.png",
  },
  {
    id: "14",
    companyId: "3",
    name: "CIC Plan III",
    tier: "Plan III",
    planType: "Enhanced",
    eligibilityAge: "65-85",
    inpatientCoverageLimit: 1000000,
    outpatientCoverageLimit: 100000,
    lastExpenseCover: 70000,
    premium: 68000, // Using approximate figure based on comparable plans
    bedLimit: "General Ward Bed",
    roomRate: "General Ward",
    companyName: "CIC Insurance",
    companyLogo: "/cic.png",
  },
  {
    id: "15",
    companyId: "3",
    name: "CIC Plan IV",
    tier: "Plan IV",
    planType: "Premium",
    eligibilityAge: "65-85",
    inpatientCoverageLimit: 2000000,
    outpatientCoverageLimit: 200000,
    lastExpenseCover: 100000,
    premium: 85000, // Using approximate figure based on comparable plans
    bedLimit: "Standard Private Room up to 15,000",
    roomRate: "Private Room",
    companyName: "CIC Insurance",
    companyLogo: "/cic.png",
  },
  {
    id: "16",
    companyId: "3",
    name: "CIC Plan V",
    tier: "Plan V",
    planType: "Executive",
    eligibilityAge: "65-85",
    inpatientCoverageLimit: 3000000,
    outpatientCoverageLimit: 200000,
    lastExpenseCover: 100000,
    premium: 120000, // Using approximate figure based on comparable plans
    bedLimit: "Standard Private Room up to 16,000",
    roomRate: "Private Room",
    companyName: "CIC Insurance",
    companyLogo: "/cic.png",
  },
  {
    id: "17",
    companyId: "3",
    name: "CIC Plan VI",
    tier: "Plan VI",
    planType: "Royal",
    eligibilityAge: "65-85",
    inpatientCoverageLimit: 5000000,
    outpatientCoverageLimit: 200000,
    lastExpenseCover: 100000,
    premium: 150000, // Using approximate figure based on comparable plans
    bedLimit: "Standard Private Room up to 20,000",
    roomRate: "Deluxe Private Room",
    companyName: "CIC Insurance",
    companyLogo: "/cic.png",
  },
];


// Common exclusions across plans
export const commonExclusions = [
  "Cosmetic or beauty treatment and/or surgery unless necessitated by an accident",
  "Massage treatments (except where medically prescribed)",
  "Naval, military and air force operations",
  "Expenses recoverable under any other insurance (e.g., NHIF, GPA)",
  "Self-inflicted injuries, suicide attempts, or treatment of alcoholism",
  "Experimental treatments or unproven medical treatments",
  "Weight management treatments and drugs",
  "Participation in professional or hazardous sports",
  "Participation in riots, strikes, and civil commotion",
  "Nutritional supplements unless prescribed as part of medical treatment",
  "Elective cosmetic procedures",
  "Alternative treatments such as herbal medicine, acupuncture, etc.",
];

